__init__.py: h5kgOguxET9c8f696KUOSoTU7ix9Km9ytWONUi4C
_config.py: load_ssl_context verify=True cert=None trust_env=True http2=False
_config.py: load_verify_locations cafile='/home/hilla/code/10Academy-training/week3/redash_chatbot_LLM/.venv/lib/python3.10/site-packages/certifi/cacert.pem'
connectionpool.py: Starting new HTTP connection (1): nginx:80
__init__.py: HTTPConnectionPool(host='nginx', port=80): Max retries exceeded with url: /api/data_sources (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ca20938bfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
selector_events.py: Using selector: EpollSelector
logging.py: Running on http://0.0.0.0:5002 (CTRL + C to quit)
